name: dotnet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    
    - name: Install Az Func
      run: npm i -g azure-functions-core-tools@4 --unsafe-perm true
       
    - name: cd
      run: 'cd src\PoeFetchLatestPatch'

    - name: pwd
      run: pwd
      
    - name: dir
      run: dir

    - name: Deploy
      run: func azure functionapp publish func-poepatch-prod-001 --force
